### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kdungs** [lhcb/analysis-essentials#15]

**Comment by betatim** [comment]
Can we haz like one sentence description please :smiley_cat:

**Comment by chrisburr** [comment]
@dberzano @kdungs @alexpearce @goi42 @betatim @dominikmuller @FedericaLionetto

You've all contributed to this repository at some point, as it gets more popular we should really add a license. I suggest we go with [Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/legalcode).

Does anyone object to this? React to this comment with a :+1: to agree else comment if you have any thoughts on this.

**Comment by goi42** [comment]
No objections.

**Comment by dominikmuller** [comment]
Sure, no objections

**Comment by dberzano** [comment]
We should be careful about relicensing content in general: most of it comes from Software Carpentry which uses [CC without the "Share Alike"](https://software-carpentry.org/license/) clause, so we could also use another license. But I agree that CC 4.0 is fine, we should just define what type of CC (BY, ND, etc.) and we can use the following link to guide us:

https://creativecommons.org/choose/

For the record: Software Carpentry uses the "CC Attribution" license, which allows relicensing, commercial use, modifications.

* Do we agree upon commercial use of our lessons?
* Do we want derivatives to be shared with the same license?

**Comment by chrisburr** [comment]
My suggestion is to use the same variant as Software Carpentry. If anyone would rather use one of the more restrictive variants then I suggest they present their reasoning here for us to discuss.

**Comment by betatim** [comment]
I agree to my contributions to this repository to be licensed under https://creativecommons.org/licenses/by/4.0/legalcode

---

I am not sure we could change the license for the material that is "copy&pasted" from the SWC materials. AFAIK all we can do is license derivatives or new work combined with it under a different license. But then I am not a lawyer etc.

**Comment by FedericaLionetto** [comment]
Hi everyone,

I’m fine with Chris proposal, it’s probably the simplest thing to do.

Cheers,

Federica

**Comment by eduardo-rodrigues** [comment]
May I ask, @chrisburr, what's the status of this (very good) move? From experience, the more you wait the trickier it gets ... ;-)
