### ISSUE TITLE
website does not reflect latest version

### ISSUE THREAD

**Issue by goi42** [lhcb/analysis-essentials#20]
Not sure why, but the changes I made in my recent pull request do not show up on the website even though I can see them here in the repo.

**Comment by chrisburr** [comment]
Do you mean the changes in lhcb/starterkit-lessons#25? If so I can see them, for example:

https://lhcb.github.io/starterkit-lessons/first-analysis-steps/files-from-grid.html

Is there somewhere you can see the old lessons?

**Comment by goi42** [comment]
No, I’m talking about the analysis-essentials site, not the starterkit lessons. For instance, the persistent-screen lesson includes a sample function at the end in the repository <https://github.com/lhcb/analysis-essentials/blob/master/shell/persistent-screen.md> but this function does not appear on the website <https://lhcb.github.io/analysis-essentials/shell/persistent-screen.html>.

**Comment by chrisburr** [comment]
Ah sorry I hadn't recognised your username in that PR!

Well spotted I think I've fixed it with d95c7da 👍
