### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by betatim** [lhcb/analysis-essentials#3]
- We need to ask people to install `git` in their lxplus accounts/laptops, last time I checked the version you get by default is old-dot-ancient and has trouble with https fetch/push.
- anaconda on their laptops/lxplus

Or should we make an anaconda install on a public AFS directory that has all the things including `git` and they simply prepend that to their `PATH`?

Or we prepare a shared anaconda for those who don't manage to install stuff themselves, and say the default is that they install it in their homedir/laptop?

**Comment by alexpearce** [comment]
The version of `git` on lxplus is now super recent as it's bundled with LbScripts. We've moved away from getting things installed directly on people's laptops as it takes too long, and we can get what we need on lxplus.
