### ISSUE TITLE
Python material

### ISSUE THREAD

**Issue by betatim** [lhcb/analysis-essentials#5]
Is it a good idea to base the `python` material around an example like:

https://gist.github.com/betatim/10f5c4669d79f6d09ca0

To make it a bit more "real" than calculating factorials etc?

I'd split it up into multiple little files doing things in steps instead of a notebook. Allows you to show how to do "calculations", store stuff to disk, read it back, make plots. With classes and functions etc thrown in "on the side".

Let me know what you think

**Comment by alexpearce** [comment]
Considering this closed by #23, which has a practical introduction to some analysis modules.
