### ISSUE TITLE
Move to “hep-starterkit” organisation

### ISSUE THREAD

**Issue by chrisburr** [lhcb/analysis-essentials#51]
I propose we move this repository to the new @hep-starterkit organisation in the hope that it can be used more generally than LHCb. Does any one have any thoughts? @alexpearce @andriiusachov @apuignav @dberzano @rbertens @vbellee @vlisovsk + everyone else

**Comment by apuignav** [comment]
I agree, it's a good move.

**Comment by eduardo-rodrigues** [comment]
We've just had discussions around training and documentation here at the PyHEP workshop in Sofia (https://indico.cern.ch/event/694818/timetable/). There is a clear interest in having training material shared among the community, and a consensus that the HSF should help. With that in mind, I would rather suggest to create a repository on the HSF GitHub (https://github.com/HSF/) dedicated to training and education (so create https://github.com/HSF/training), and have the HEP-general starterkit as a first repository under that. 

This would be a clear message to all and also a really nice outcome/action of/from PyHEP, if I may add.

**Comment by chrisburr** [comment]
@eduardo-rodrigues I'm happy for the HSF to coordinate this shared effort though I don't understand the structure you're proposing. Do you mean add it as https://github.com/HSF/general-starterkit (as https://github.com/HSF/training/general-starterkit isn't possible)?

It might be nicer to have a single training or documentation organisation. I can transfer ownership of hep-starterkit or we could create hsf-training/hsf-starterkit/something similar.

**Comment by chrisburr** [comment]
(from private discussions) The preferred option appears to be to make a hsf-training organisation and move this there. I will probably do it later today if there are no objections.
